### ISSUE TITLE
Request for a BLE example

### ISSUE THREAD

**Issue by csukuangfj** [sparkfun/SparkFun_Edge_BSP#8] opened 2019-06-17 13:20 UTC
Hi, 

Information displayed with the on-board LEDs is too limited.
could you please upload a BLE example for the Sparkfun edge board?

**Comment by oclyke** [comment] 2019-06-17 15:54
Hi @csukuangfj,

Since Bluetooth is independent of board variants you will be able to compile and test one of the examples for the Apollo3 EVB with little to no modification.

Try copying the 'ble_fit' example from 'boards/Apollo3_EVB/examples' into the Edge_BSP/examples folder. Then add the targets in your makefile for 'make bootload' (You'll need to add things like the COM/SERIAL_PORT -- just use one of the existing makefiles as an example to get you started.)

**Comment by csukuangfj** [comment] 2019-06-18 03:19
Hi @oclyke 
thank you for your reply.

I cannot find the `ble_fit` example in `boards/Apollo3_EVB/examples`, but there is an example `freertos_fit_lp`. I have copied it to the `SparkFun_Edge_BSP/examples`.

And I changed the `gcc/Makefile` to

```
--- ../../../../apollo3_evb/examples/freertos_fit_lp/gcc/Makefile	2019-01-20 16:18:16.000000000 +0800
+++ Makefile	2019-06-18 11:05:53.000000000 +0800
@@ -37,6 +37,18 @@
 # This is part of revision v2.0.0 of the AmbiqSuite Development Package.
 #
 #******************************************************************************
+
+OS = $(shell uname -s)
+ifeq ($(OS),Linux)
+	COM_PORT = /dev/ttyUSB0
+else
+	COM_PORT = /dev/cu.wchusbserial1420
+endif
+SDKPATH				 = ../../../../..# Note that if you copy/paste a windows file path here you need to change backslashes to forward slashes
+BOARDPATH			 = ${SDKPATH}/boards/SparkFun_Edge_BSP# Set this as the path to the SparkFun Edge BSP (Board Support Package) directory. Initially assumes that you put the BSP under the 'boards' directory in the SDK
+
+SERIAL_PORT ?= ${COM_PORT} # This can be overridden in another file
+
 TARGET := freertos_fit_lp
 COMPILERNAME := gcc
 PROJECT := freertos_fit_lp_gcc
@@ -308,6 +320,13 @@
 ../../../bsp/gcc/bin/libam_bsp.a:
 	$(MAKE) -C ../../../bsp

+wired_update: all
+	${SDKPATH}/tools/apollo3_scripts/create_cust_image_blob.py --bin $(CONFIG)/$(TARGET).bin --load-address 0xC000 --magic-num 0xCB -o $(CONFIG)/main_nonsecure_ota --version 0x0
+	${SDKPATH}/tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin $(CONFIG)/main_nonsecure_ota.bin -i 6 -o $(CONFIG)/main_nonsecure_wire --options 0x1
+
+bootload: wired_update
+	${BOARDPATH}/bsp/tools/uart_wired_update_sparkfun.py -b 115200 $(SERIAL_PORT) -r 1 -f $(CONFIG)/main_nonsecure_wire.bin -i 6
+
 # Automatically include any generated dependencies
 -include $(DEPS)
 endif
```

But when I run `make bootload`, it throws the following error:

```
AmbiqSuite-Rel2.0.0/boards/SparkFun_Edge_BSP/examples/freertos_fit_lp/gcc$ make bootload
../../../../../tools/apollo3_scripts/create_cust_image_blob.py --bin bin/freertos_fit_lp.bin --load-address 0xC000 --magic-num 0xCB -o bin/main_nonsecure_ota --version 0x0
Header Size =  0x80
original app_size  0x18f34 ( 102196 )
load_address  0xc000 ( 49152 )
app_size  0x18f34 ( 102196 )
w0 = 0xcb018fb4
Security Value  0x10
w2 =  0x10008080
addrWord =  0xc000
versionKeyWord =  0x0
child0/feature =  0xffffffff
child1 =  0xffffffff
crc =   0x83fe5567
Writing to file  bin/main_nonsecure_ota.bin
../../../../../tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin bin/main_nonsecure_ota.bin -i 6 -o bin/main_nonsecure_wire --options 0x1
Header Size =  0x60
app_size  0x18fb4 ( 102324 )
Writing to file  bin/main_nonsecure_wire.bin
Image from  0x0  to  0x18fb4  will be loaded at 0x20000
../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 115200 /dev/cu.wchusbserial1420  -r 1 -f bin/main_nonsecure_wire.bin -i 6
Connecting with Corvette over serial port /dev/cu.wchusbserial1420...
Sending Hello.
Received response for Hello
Received Status
length =  0x58
version =  0x3
Max Storage =  0x4ffa0
Status =  0x2
State =  0x7
AMInfo =
0x1
0xff2da3ff
0x55fff
0x1
0x49f40003
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
Sending OTA Descriptor =  0xfe000
Sending Update Command.
number of updates needed =  1
Sending block of size  0x19014  from  0x0  to  0x19014
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  4260
Sending Reset Command.
No response for command 0x00000006
received bytes  19
['0xb7', '0xa5', '0x61', '0x81', '0x7', '0x0', '0x14', '0x0', '0x6', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']
Traceback (most recent call last):
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 341, in <module>
    main()
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 42, in main
    connect_device(ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 175, in connect_device
    send_ackd_command(resetmsg, ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 194, in send_ackd_command
    response = send_command(command, 20, ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 238, in send_command
    raise NoResponseError
__main__.NoResponseError
make: *** [bootload] Error 1
```

I did press the reset button when it says `Sending Reset Command.` but it still throws the above error.

Is there anything that I should do to avoid the above error?

Thank you.

**Comment by oclyke** [comment] 2019-06-18 16:15
@csukuangfj this looks promising! I see that you are using a serial baud rate of 115200 -- this is OK and expected as long as you received your Edge board from the TensorFlow summit. (It appears to be working b/c the Hello msg was received and data transferred)

I have experienced the error you are seeing on occasion and I suspect it has to do with the settings for the bootloader - which are not easily changed except with a JTAG/SWD programmer. 

However that error does not necessarily mean that the code will not work. Are you able to see the BLE device show up using an app such as NRF Connect? And if that does not work consider adding some "blink" code (or a printf statement after configuring the uart) to see if the code has been properly loaded + executed. 

We're working on a big improvement to the bootloader to avoid these problems in the future!

**Comment by csukuangfj** [comment] 2019-06-21 01:48
@oclyke 
I have installed an nRF Connect App from NORDIC on my phone. However, it shows no devices.
I suspect that the code does not work on the Edge board. Have you ever tried to run a BLE
application on the Edge board?

**Comment by metanav** [comment] 2019-06-25 10:59
I compiled and uploaded freertos_fit example. I can see "Fit" in the bluetooth scan list in my Android phone. So the BLE works. But modifying this code for my own work is a terribly difficult task. I would like to see some simple example to initialize the BLE and connect to it  to get some data for example, accelerometer readings.

**Comment by csukuangfj** [comment] 2019-06-26 01:51
@metanav

I agree with you. 

In addition, a working example without any OS is much easier to port.

**Comment by oclyke** [comment] 2019-06-26 21:05
@metanav and @csukuangfj We hear you - we'll try to do this in the future. I can't give a definite timeframe so for now I'd recommend digging into the Ambiq HAL functions. 

Here's a nudge in the right direction thanks to one of the folk at Ambiq

> In the SDK there is the Ambiq Micro Data Transfer Profile (AMDTP) example:
> <USER_PATH>\AmbiqSuite-Rel2.1.0\docs\app_notes\amdtp\ AMDTP_example_user's_guide.pdf
>
> ![image001](https://user-images.githubusercontent.com/13486034/60214895-b33e6980-9823-11e9-9189-2e5f3fddb655.png)
>
> The example projects for “client” and “server” are available here:
> <USER_PATH>\AmbiqSuite-Rel2.1.0\boards\apollo3_evb\examples\ble_freertos_amdtps
> <USER_PATH>\AmbiqSuite-Rel2.1.0\boards\apollo3_evb\examples\ble_freertos_amdtpc
> 
>![image002](https://user-images.githubusercontent.com/13486034/60214905-be919500-9823-11e9-89ac-e5edacdd9b60.png)
> 
> I have had one other partner use AMDTP to develop a demo using BLE and an iOS APP.

**Comment by metanav** [comment] 2019-07-01 05:25
I tried to use the AMDTP example. It works ( I can connect and see characteristics) but still I am not able to transfer data from the Edge board to the app (LightBlue on Android) via BLE. The reason is AMDTP server  gets hung whenever client tries to write on the ACK CCCD which is required to enable ACK characteristics. Also I think this example is best suited with two Edge boards one as a server and another one as a client. I wish SparkFun could post a simple working example soon.

**Comment by metanav** [comment] 2019-07-03 06:46
Finally I was able to reuse freertos_fit example to stream accelerometer data to app over ble.

**Comment by oclyke** [comment] 2019-07-03 14:35
Awesome! Did you find the cause for the hang when writing to the ACK CCCD?

**Comment by metanav** [comment] 2019-07-04 05:31
I was not able to debug AMDTP example.

**Comment by wangtz** [comment] 2019-07-16 13:39
@metanav Hi Naveen, I'm looking into a simple BLE streaming demo as well. Wondering if a simplified version of your code will be open sourced. Thanks!

**Comment by oclyke** [comment] 2019-12-02 21:28
Hi all - if you'd like you can check out the BLE example in the updated (LTS) BSP repo:
https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs

And you can go 'easy mode' with this repo:
https://github.com/sparkfun/AmbiqSuiteSDK

And lastly if you want to try out a Docker build env. try this:
https://github.com/sparkfun/artemis_dev_platform

**Closed by oclyke** 2019-12-02 21:28 UTC

**Comment by BerndHuber** [comment] 2019-12-06 14:09
@metanav Which demo did you get to work that actually sends some data? The ble_cordio_tag example seems to only connect but not send some data. Would be awesome to have a basic example.

**Comment by metanav** [comment] 2019-12-06 14:49
@BerndHuber I used this one: AmbiqSuite-Rel2.0.0/boards/apollo3_evb/examples/freertos_fit

**Comment by BerndHuber** [comment] 2019-12-06 15:21
@metanav How did you compile freertos_fit for SparkFun edge?

I tried
```

cd AmbiqSuite-Rel2.0.0/boards/apollo3_evb/examples/freertos_fit/gcc
make              # build project
make bootload     # equivalent to 'bootload_svl'
make bootload_svl # bootloads using the SparkFun Variable Loader
make bootload_asb # bootloads using the Ambiq Secure Bootloader - overwrites SparkFun Variable Loader

```
But I am getting:

> make: *** No rule to make target `bootload'.  Stop.

**Comment by metanav** [comment] 2019-12-06 15:25
@BerndHuber  compare the Makefile with  one of the Sparkfun examples Makefile and change accordingly.

**Comment by BerndHuber** [comment] 2019-12-06 17:08
I compiled the binary but keep getting this error message when loading it on the board:

Sending Data Packet of length  1880
Received NACK
msgType =  0x8
error =  0x4
seqNo =  0x0

Could you share the makefile that worked for you?

**Comment by metanav** [comment] 2019-12-07 02:59
Here is relevant snippet of the Makefile:

```
SERIAL_PORT ?= /dev/tty.wchusbserial1440
wired_update: all
        ../../../../../tools/apollo3_scripts/create_cust_image_blob.py --bin $(CONFIG)/$(TARGET).bin --load-address 0xC000 --magic-num 0xCB -o $(CONFIG)/main_nonsecure_ota --version 0x0
        ../../../../../tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin $(CONFIG)/main_nonsecure_ota.bin -i 6 -o $(CONFIG)/main_nonsecure_wire --options 0x1

bootload: wired_update
        ../../../bsp/tools/uart_wired_update_sparkfun.py -b 921600 $(SERIAL_PORT) -r 1 -f $(CONFIG)/main_nonsecure_wire.bin -i 6

boot_artemis: wired_update
        ${ARTEMIS_LOADER_CMD} -b 921600 $(SERIAL_PORT) -r 1 -f $(CONFIG)/main_nonsecure_wire.bin -i 6 -v
```

But I think you have no issue with compilation. How are you flashing? Are you holding RST and BTN 14 together and releasing RST while flashing?

**Comment by brandPittCode** [comment] 2020-06-23 14:15
> Here is relevant snippet of the Makefile:
> 
> ```
> SERIAL_PORT ?= /dev/tty.wchusbserial1440
> wired_update: all
>         ../../../../../tools/apollo3_scripts/create_cust_image_blob.py --bin $(CONFIG)/$(TARGET).bin --load-address 0xC000 --magic-num 0xCB -o $(CONFIG)/main_nonsecure_ota --version 0x0
>         ../../../../../tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin $(CONFIG)/main_nonsecure_ota.bin -i 6 -o $(CONFIG)/main_nonsecure_wire --options 0x1
> 
> bootload: wired_update
>         ../../../bsp/tools/uart_wired_update_sparkfun.py -b 921600 $(SERIAL_PORT) -r 1 -f $(CONFIG)/main_nonsecure_wire.bin -i 6
> 
> boot_artemis: wired_update
>         ${ARTEMIS_LOADER_CMD} -b 921600 $(SERIAL_PORT) -r 1 -f $(CONFIG)/main_nonsecure_wire.bin -i 6 -v
> ```
> 
> But I think you have no issue with compilation. How do you do flashing? Are you holding RST and BTN 14 together and releasing RST while flashing?



> @BerndHuber I used this one: AmbiqSuite-Rel2.0.0/boards/apollo3_evb/examples/freertos_fit

Thanks, I used the same example and it worked. But now, after successfully modifying the code to send data to a windows Python client, the BLE unexpectedly stop working and the device won't be found anymore. I have two Sparkfun edge cards, I had this problem with one, so I switched to the other one, but know I have the same problem with the other one. Have you got the same problem. Do you still work with this device?

**Comment by brandPittCode** [comment] 2020-06-23 14:15
> @BerndHuber I used this one: AmbiqSuite-Rel2.0.0/boards/apollo3_evb/examples/freertos_fit

Thanks, I used the same example and it worked. But now, after successfully modifying the code to send data to a windows Python client, the BLE unexpectedly stop working and the device won't be found anymore. I have two Sparkfun edge cards, I had this problem with one, so I switched to the other one, but know I have the same problem with the other one. Have you got the same problem? Do you still work with this device?

**Comment by metanav** [comment] 2020-06-23 14:22
I think the BLE advertisement time is around 30s and you need to connect to it as soon it is started or try to increase the advertisement time.

**Comment by brandPittCode** [comment] 2020-06-23 14:29
> I think the BLE advertisement time is around 30s and you need to connect to it as soon it is started or try to increase the advertisement time.

Actually it has worked before, it has just now stopped being found as a BLE device.

**Comment by diego-lima** [comment] 2020-08-04 23:58
> Actually it has worked before, it has just now stopped being found as a BLE device.

@brandPittCode  Did you try unbonding the connected device?

Also, could you share how you managed to successfully modify the code to send data through BLE?

**Comment by diego-lima** [comment] 2020-08-05 00:19
I really wish I could find some basic examples on writing data through BLE just as I did through serial (UART).

I am unable to write this kind of code on my own, and I am struggling to find any resources to learn from.
